"""empty message

Revision ID: 19c084e31c06
Revises: d2124cb345f5
Create Date: 2023-04-15 12:18:31.052657

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19c084e31c06'
down_revision = 'd2124cb345f5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_table', sa.Column('admin_bot', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_table', 'admin_bot')
    # ### end Alembic commands ###
