"""empty message

Revision ID: 3c006f7c4d8e
Revises: 19c084e31c06
Create Date: 2023-04-16 08:32:16.997573

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c006f7c4d8e'
down_revision = '19c084e31c06'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blacklist',
    sa.Column('id_telegram', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=32), nullable=True),
    sa.Column('role', sa.String(length=16), nullable=True),
    sa.PrimaryKeyConstraint('id_telegram'),
    sa.UniqueConstraint('id_telegram')
    )
    op.drop_column('user_table', 'admin_bot')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_table', sa.Column('admin_bot', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_table('blacklist')
    # ### end Alembic commands ###
