"""editColumnDescriptionAbout

Revision ID: 769b0ad4b443
Revises: b8632b08970c
Create Date: 2023-04-10 18:26:33.937565

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '769b0ad4b443'
down_revision = 'b8632b08970c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('description_seller', 'about_seller',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.create_unique_constraint(None, 'super_admin', ['id_telegram'])
    op.create_unique_constraint(None, 'user_table', ['id_telegram'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_table', type_='unique')
    op.drop_constraint(None, 'super_admin', type_='unique')
    op.alter_column('description_seller', 'about_seller',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    # ### end Alembic commands ###
