"""create tables

Revision ID: b8632b08970c
Revises: 
Create Date: 2023-04-05 16:40:31.141286

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8632b08970c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('description_costumer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('about_costumer', sa.Text(), nullable=True),
    sa.Column('instruction_costumer', sa.Text(), nullable=True),
    sa.Column('regulations_costumer', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('description_seller',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('about_seller', sa.Text(), nullable=True),
    sa.Column('instruction_seller', sa.Text(), nullable=True),
    sa.Column('regulations_seller', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('market_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=32), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('location', sa.String(length=32), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('datetime_subscription', sa.DateTime(), nullable=True),
    sa.Column('datetime_registration', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('super_admin',
    sa.Column('id_telegram', sa.Integer(), nullable=False),
    sa.Column('photo_bot', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id_telegram'),
    sa.UniqueConstraint('id_telegram')
    )
    op.create_table('categories_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=True),
    sa.Column('market_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['market_id'], ['market_table.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_table',
    sa.Column('id_telegram', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=32), nullable=True),
    sa.Column('like', sa.Integer(), nullable=True),
    sa.Column('dislike', sa.Integer(), nullable=True),
    sa.Column('role', sa.String(length=16), nullable=True),
    sa.Column('market_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['market_id'], ['market_table.id'], ),
    sa.PrimaryKeyConstraint('id_telegram'),
    sa.UniqueConstraint('id_telegram')
    )
    op.create_table('firm_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=32), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories_table.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=32), nullable=True),
    sa.Column('amount_20mg', sa.Integer(), nullable=True),
    sa.Column('amount_45mg', sa.Integer(), nullable=True),
    sa.Column('price_for_1', sa.Integer(), nullable=True),
    sa.Column('price_for_10', sa.Integer(), nullable=True),
    sa.Column('price_for_25', sa.Integer(), nullable=True),
    sa.Column('price_for_100', sa.Integer(), nullable=True),
    sa.Column('firm_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['firm_id'], ['firm_table.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product_table')
    op.drop_table('firm_table')
    op.drop_table('user_table')
    op.drop_table('categories_table')
    op.drop_table('super_admin')
    op.drop_table('market_table')
    op.drop_table('description_seller')
    op.drop_table('description_costumer')
    # ### end Alembic commands ###
