"""empty message

Revision ID: d2124cb345f5
Revises: e8eec3f9dee5
Create Date: 2023-04-15 14:04:58.572522

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2124cb345f5'
down_revision = 'e8eec3f9dee5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_table', sa.Column('blacklist', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_table', 'blacklist')
    # ### end Alembic commands ###
