"""empty message

Revision ID: db7765e2ba0f
Revises: 769b0ad4b443
Create Date: 2023-04-10 18:34:43.548543

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db7765e2ba0f'
down_revision = '769b0ad4b443'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('description_seller', 'about_seller',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.create_unique_constraint(None, 'super_admin', ['id_telegram'])
    op.create_unique_constraint(None, 'user_table', ['id_telegram'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_table', type_='unique')
    op.drop_constraint(None, 'super_admin', type_='unique')
    op.alter_column('description_seller', 'about_seller',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    # ### end Alembic commands ###
