"""empty message

Revision ID: e8eec3f9dee5
Revises: db7765e2ba0f
Create Date: 2023-04-10 19:18:22.258685

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8eec3f9dee5'
down_revision = 'db7765e2ba0f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('description_costumer')
    op.add_column('description_seller', sa.Column('about_costumer', sa.Text(), nullable=True))
    op.add_column('description_seller', sa.Column('instruction_costumer', sa.Text(), nullable=True))
    op.add_column('description_seller', sa.Column('regulations_costumer', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('description_seller', 'regulations_costumer')
    op.drop_column('description_seller', 'instruction_costumer')
    op.drop_column('description_seller', 'about_costumer')
    op.create_table('description_costumer',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('about_costumer', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('instruction_costumer', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('regulations_costumer', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='description_costumer_pkey')
    )
    # ### end Alembic commands ###
